Yolov4:
    onnx_file:     "../yolov4-tiny.onnx"
    engine_file:   "../yolov4-tiny.trt"
    labels_file:   "../coco.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   416
    IMAGE_HEIGHT:  416
    obj_threshold: 0.4
    nms_threshold: 0.45
    new_coords:    False
    strides:       [16, 32]
    num_anchors:   [ 3,  3]
    anchors:       [[ 23, 27], [ 37, 58], [ 81, 82], [ 81, 82], [135, 169], [ 344, 319]]
