Yolov4:
    onnx_file:     "../yolov4-csp.onnx"
    engine_file:   "../yolov4-csp.trt"
    labels_file:   "../coco.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   512
    IMAGE_HEIGHT:  512
    obj_threshold: 0.4
    nms_threshold: 0.6
    new_coords:    True
    letter_box:    True
    strides:       [8, 16, 32]
    num_anchors:   [3,  3,  3]
    anchors:       [[12, 16], [19, 36], [40, 28], [36, 75], [76, 55], [72, 146], [142, 110], [192, 243], [459, 401]]
