ScaledYOLOv4:
    onnx_file:     "../yolov4-p7.onnx"
    engine_file:   "../yolov4-p7.trt"
    labels_file:   "../coco.names"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   1536
    IMAGE_HEIGHT:  1536
    obj_threshold: 0.4
    nms_threshold: 0.45
    strides:       [8, 16, 32, 64, 128]
    num_anchors:   [4,  4,  4,  4,   4]
    anchors:       [[ 13, 17], [ 22, 25], [ 27, 66], [ 55, 41], [ 57, 88], [ 112, 69], [ 69, 177], [ 136, 138], [ 136, 138], [ 287, 114], [ 134, 275], [ 268, 248], [ 268, 248], [ 232, 504], [ 445, 416], [ 640, 640], [ 812, 393], [ 477, 808], [1070, 908], [1408,1408]]
